[package]
name = "insider-metric-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
insider-common-types = { path = "../common-types" }
insider-metric-sdk = { path = "../metric-sdk" }
insider-scheduler = { path = "../scheduler" }
serde_json = "1"
