[package]
name = "insider-reconciliation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
insider-broker-api = { path = "../broker-api" }
insider-common-types = { path = "../common-types" }
insider-execution = { path = "../execution" }
